branch-defaults:
  master:
    environment: DockerReact-env
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: docker-react
  default_ec2_keyname: AwsKeyPairEc2
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on 64bit Amazon Linux 2/3.2.0
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
